spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/archer?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 9

# Dubbo
dubbo:
  registry:
    protocol: zookeeper
    address: localhost:21823
    timeout: 60000